name: Build MacOS

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.0

      - name: Install gogio tool
        run: make install_deps

      - name: Install create-dmg tool
        run: brew install create-dmg

      - name: Generate macOS icon
        run: |
          chmod +x ./assets/png_to_icns.sh
          ./assets/png_to_icns.sh

      - name: Build macos disk images
        run: |
          make build_macos_app
          make build_macos_dmg

      - name: Upload Release Asset
        run: |
          gh release upload ${{github.event.release.tag_name}} ./dist/debrief-macos-${{ github.ref_name }}-amd64.dmg
          gh release upload ${{github.event.release.tag_name}} ./dist/debrief-macos-${{ github.ref_name }}-arm64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
